'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Persona
    Public Property id As Integer
    Public Property primerNombre As String
    Public Property segundoNombre As String
    Public Property primerApellido As String
    Public Property segundoApellido As String
    Public Property fechaNac As Date
    Public Property sexo As Nullable(Of Boolean)
    Public Property telefono As String
    Public Property email As String
    Public Property idCiudad As Nullable(Of Integer)
    Public Property direccion As String
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property Ciudad As Ciudad

End Class
